services:
  app:
    build:
      context: .
      target: production
    env_file:
      - .env
    environment:
      - ConnectionStrings__Default=${POSTGRES_CONNECTION}
      - Jwt__Secret=${JWT__SECRET}
      - Jwt__Issuer=${JWT__ISSUER}
      - Jwt__Audience=${JWT__AUDIENCE}
      - Jwt__ExpirationHours=${JWT__EXPIRATIONHOURS}
    restart: always
    networks:
      - proxy

networks:
  proxy:
    external: true