services:
  api:
    container_name: neon-vertex-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__Default=${MSSQL_CONNECTION:?MSSQL_CONNECTION is required}
    networks:
      - home-network

networks:
  home-network:
    external: true
