name: neon-vertex

services:
  api:
    image: neon-vertex-api:latest
    build:
      context: .
      target: production
    environment:
      - ConnectionStrings__Default=${MSSQL_CONNECTION}
      - Jwt__Secret=${JWT__SECRET}
      - Jwt__Issuer=${JWT__ISSUER:-NeonVertexApi}
      - Jwt__Audience=${JWT__AUDIENCE:-NeonVertexApi}
      - Jwt__ExpirationHours=${JWT__EXPIRATIONHOURS:-24}
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
